app_main/urls.py
from django.urls import path
from .views import views, cards_view, transfer_view, service_view, destinatary_view, destinatary_view, history_view

app_name = 'system'

urlpatterns = [
     # Pagina de inicio
     path('', views.IndexView.as_view(), name='home'),
     # historial
     path('history/', history_view.HistorialView.as_view(), name='history'),
     
     path('terms_conditions/', views.TermsView.as_view(), name='terms_conditions'),
     path('contact/', views.ContactView.as_view(), name='contact'),
     path('main/', views.MainView.as_view(), name='main'),
     # Servicios
     path('service_list/', service_view.ServiceListView.as_view(), name='service_list'),
     path('service_create/', service_view.ServiceCreateView.as_view(), name='service_create'),
     path('service_update/<int:pk>', service_view.ServiceUpdateView.as_view(), name='service_update'),
     path('service_delete/<int:pk>', service_view.ServiceDeleteView.as_view(), name='service_delete'),
     path('service_pay/<int:pk>', service_view.ServicePayView.as_view(), name='service_pay'),
     # Tarjetas
     path('card_list/', cards_view.CardListView.as_view(), name='card_list'),
     path('card_create/',
          cards_view.CardCreateView.as_view(), name='card_create'),
     path('card_delete/<int:pk>',
          cards_view.CardDeleteView.as_view(), name='card_delete'),
     # Transferencias
     path('transfer_create/',
          transfer_view.TranferCreateView.as_view(), name='transfer_create'),
     path('transfer_list/',
          transfer_view.TranferListView.as_view(), name='transfer_list'),
     # Destinatarios
     path('destinatary_list/',
          destinatary_view.DestinataryListView.as_view(), name='destinatary_list'),
     path('destinatary_delete/<int:pk>',
          destinatary_view.DestinataryDeleteView.as_view(), name='destinatary_delete'),
     path('destinatary_create/',
          destinatary_view.DestinataryCreateView.as_view(), name='destinatary_create'),
     path('destinatary_update/<int:pk>',
          destinatary_view.DestinataryUpdateView.as_view(), name='destinatary_update')                    

]

app_users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', UsersLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    
    path('editprofile/<int:pk>/', UserUpdateView.as_view(), name='editprofile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('segurity/', SegurityUserView.as_view(), name='segurity')
]

project_EZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')),
    path('', include('app_users.urls'))
]

app_main/views/cards_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *


class CardListView(LoginRequiredMixin, ListView):
    model = User_Card
    template_name = 'card/credit_card.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        cards_list = User_Card.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Tarjetas'
        context['title'] = 'Agregar Tarjeta'
        context['entity'] = User_Card
        context['object_list'] = cards_list
        context['action'] = 'add'
        context['data'] = self.request.session.pop('data', None)

        return context


class CardCreateView(LoginRequiredMixin, CreateView):
    model = User_Card
    form_class = CardForm
    template_name = 'card/credit_card.html'
    success_url = reverse_lazy('system:card_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    card = Bank_DB.objects.get(
                        card_number=request.POST['card_number'])
                    if not card.associated:
                        if request.POST['pin'] == card.pin:
                            form.instance.user = self.request.user
                            form.instance.bank_type = card.bank_type
                            form.instance.currency_type = card.currency_type
                            form.instance.balance = card.balance
                            card.associated = True

                            card.save()
                            form.save()
                            data['form_is_valid'] = True
                        else:
                            data['error'] = 'Pin incorrecto'
                    else:
                        data['error'] = 'La tarjeta ya está asociada a un usuario!'
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'
        
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta de no existe'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'La tarjeta ha sido creada con éxito.'}
            print(request.session['data'])
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'User_Card'
        context['list_url'] = reverse_lazy('card_create')

        return context


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = User_Card
    success_url = reverse_lazy('system:card_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:

            user_card = User_Card.objects.get(id=self.object.id)
            bank_card = Bank_DB.objects.get(card_number=user_card.card_number)

            bank_card.associated = False
            bank_card.save()
        except:
            pass
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        
        context['title'] = 'Eliminar tarjeta'
        context['text'] = 'Estas seguro que desea eliminar la tarjta?'
        context['url_redirect'] = self.success_url
        return context
   
    

app_main/views/destinatary_view.py
from typing import Any, Dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *



class DestinataryListView(LoginRequiredMixin, ListView):
    model = Destinatary
    template_name = 'destinatary/destinary.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        destinatary_list = Destinatary.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Destinatarios'
        context['title'] = 'Agregar Destinatario'
        context['entity'] = Destinatary
        context['object_list'] = destinatary_list
        context['data'] = self.request.session.pop('data', None)
        context['action_update'] = 'edit'
        context['action'] = 'add'

        return context
    

class DestinataryCreateView(LoginRequiredMixin, CreateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(
                        card_number=number)
                    form.instance.user = self.request.user

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:
                        if destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)

                    form.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'

        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido creado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)
    

class DestinataryDeleteView(LoginRequiredMixin, DeleteView):
    model = Destinatary
    success_url = reverse_lazy('system:destinatary_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar destinatario'
        context['text'] = 'Está seguto de eliminar el destinatario?'
        context['url_redirect'] = reverse_lazy('system:destinatary_list')

        return context


class DestinataryUpdateView(LoginRequiredMixin, UpdateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(card_number=number)

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:

                        if self.object.associated_card == number or self.object.name == name:
                            pass
                        elif destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)
                       
                    form.save()
                    data['form_is_valid'] = True

                else:
                    data['error'] = form.errors    
                
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido actualizado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar destinatario'

        return context 

app_main/views/history_view.py
from itertools import chain
from django.contrib.contenttypes.models import ContentType
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Transfer, Service_Pay


class HistorialView(LoginRequiredMixin, ListView):
    model = Transfer
    template_name = 'historial.html'
    context_object_name = 'historial'

    def get_queryset(self):
        user = self.request.user
        transfers = Transfer.objects.filter(user=user)
        service_pays = Service_Pay.objects.filter(user=user, checked=True)

        queryset = sorted(chain(transfers, service_pays),
                          key=lambda i: i.date, reverse=True)
        for object in queryset:
            object.model_name = ContentType.objects.get_for_model(object).model
            print(object.model_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

app_main/views/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..mixins import IsSuperuserMixin

# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class MainView(LoginRequiredMixin, IsSuperuserMixin, TemplateView):
    template_name = 'main.html'


class TermsView(TemplateView):
    template_name = 'terms_conditions.html'

class ContactView(TemplateView):
    template_name = 'contactenos.html'          

app_main/templates/eliminar.html
{% extends 'base/body.html' %}

{% block content %}
<div id="main" style="border-radius: 0px;">
    <div class="text-center" data-aos="fade-down" style="border-radius: 15px;height: 500px;">
        <p style="color:white;" class="text-center" style="font-size: 20px;">{{title}}</p>
        <form method="post">
            {% csrf_token %}
            <div class="text-center px-6 py-6">
                <div class="text-center px-6 py-6">
                    <p style="color:white;">{{text}} {{object.name}}</p>
                </div>
                <a type="button" href="{{url_redirect}}" class="btn btn-secondary">Cancelar </a>
                <button type="submit" class="btn btn-danger">Confirmar </button>
            </div>
        </form>

    </div>
</div>

{% endblock %}

app_main/templates/login.html
{% extends 'base/body.html' %}
{% load static %}
{% block content %}
<div id="main" style="border-radius: 0px;">
    <div class="text-center" data-aos="fade-down" id="info" style="border-radius: 15px;height: 500px;"><img
            id="ventaspro-logo" src="{% static 'img/enzona%20-%20copia.jpg' %}" width="64" height="63"
            style="border-radius: 90px;">
        <p class="text-center" style="font-size: 20px;">{{title}}</p>
        <form class="text-center" method="POST" action=".">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}">
            <div class="mb-3 mx-4 px-4">
                <label class="form-label rubberBand animated" for="username" style="font-size: 20px;">Usuario</label>
                <input class="form-control rubberBand animated" autofocus="on" type="text" name="username"
                    style="background: rgba(255,255,255,0.79);">
            </div>
            <div class="mb-3 mx-4 px-4">
                <label class="form-label rubberBand animated" for="password" style="font-size: 20px;">Contraseña</label>
                <input class="form-control rubberBand animated" name="password" type="password"
                    style="background: rgba(255,255,255,0.79);">
            </div>
            <div class="mb-3 mx-4 px-4">
                <button class="btn btn-primary" data-bss-hover-animate="bounce" type="submit"
                    style="--bs-primary: #256db4;--bs-primary-rgb: 37,109,180;background: #256db4;font-size: 20px;">Iniciar
                    Sesión</button>
            </div>
        </form>

        <div style="margin-top: 10px;">
            <a href="{% url 'users:register' %}" style="color: rgb(255,255,255);font-size: 15px;">Registrar ahora</a>
        </div>
    </div>
</div>

{% endblock %}

app_main/templates/main.html
{% extends 'base/body.html' %}
{% block content %}
<div class="container py-4 py-xl-5">
    <div class="row gy-3 mb-5">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            <h2 style="color: rgb(255,255,255);">Bienvenido a Enzona&nbsp;</h2>
            <p></p>
        </div>
    </div>
    <div class="row gx-2 gy-5 row-cols-2 row-cols-md-2 justify-content-between">
        <div class="col-auto mx-auto" data-aos="fade-right">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100"><a href="{% url 'system:destinatary_list' %}"><i class="material-icons"
                            data-bss-hover-animate="pulse"
                            style="font-size: 139px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;">people</i></a>
                </div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Mis Destinatario</h4>
                    <p style="color: rgb(255,255,255);">Para su comodidad registre los Destinarios que utilice
                        regularmente. para realizar operaciones mas fácilmente.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp;</p>
                </div>
            </div>
        </div>
        <div class="col-auto mx-auto" data-aos="fade-left">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100"><a href="{% url 'system:transfer_list' %}"><svg xmlns="http://www.w3.org/2000/svg"
                            width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-bank"
                            data-bss-hover-animate="pulse"
                            style="font-size: 139px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;">
                            <path
                                d="M8 .95 14.61 4h.89a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v7a.5.5 0 0 1 .485.379l.5 2A.5.5 0 0 1 15.5 17H.5a.5.5 0 0 1-.485-.621l.5-2A.5.5 0 0 1 1 14V7H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 4h.89L8 .95zM3.776 4h8.447L8 2.05 3.776 4zM2 7v7h1V7H2zm2 0v7h2.5V7H4zm3.5 0v7h1V7h-1zm2 0v7H12V7H9.5zM13 7v7h1V7h-1zm2-1V5H1v1h14zm-.39 9H1.39l-.25 1h13.72l-.25-1z">
                            </path>
                        </svg></a></div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Transferencias</h4>
                    <p style="color: rgb(255,255,255);">Le permite transferir fondos a un amigo, tarjeta, cuenta de
                        ENZONA o entre sus tarjetas bancarias, siempre garantizando la disponibilidad de los fondos en
                        tiempo real.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
                </div>
            </div>
        </div>
        <div class="col-auto mx-auto" data-aos="fade-right">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100"><a href="{% url 'system:card_list' %}"><i class="material-icons"
                            data-bss-hover-animate="pulse"
                            style="font-size: 139px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;">credit_card</i></a>
                </div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Mis tarjetas</h4>
                    <p style="color: rgb(255,255,255);">Consulte y gestione los datos de cada tarjeta que tenga
                        vinculada en ENZONA.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br><br></p>
                </div>
            </div>
        </div>
        <div class="col-auto mx-auto" data-aos="fade-left">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100" style="height: 200px;"><a href="{% url 'system:service_list' %}"><i
                            class="material-icons" data-bss-hover-animate="pulse"
                            style="font-size: 137px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;margin-left: 20px;">shopping_cart</i></a>
                </div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Pago de Servicios</h4>
                    <p style="color: rgb(255,255,255);">Realice pagos de diferentes servicios de Cuba en línea . Para su
                        comodidad registre los ID de Cliente que utilice regularmente. El historial de sus pagos siempre
                        está disponible a través de<br> ENZONA.</p>
                </div>
            </div>
        </div>
        <div class="col-auto mx-auto" data-aos="fade-right">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100"><a href="{% url 'system:history' %}"><i class="material-icons text-start"
                            data-bss-hover-animate="pulse"
                            style="font-size: 139px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;margin-left: 0PX;">attach_money</i></a>
                </div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Ultimas operaciones</h4>
                    <p style="color: rgb(255,255,255);">Conozca la disponibilidad de los saldos de sus tarjetas
                        vinculadas en ENZONA.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
                </div>
            </div>
        </div>
        <div class="col-auto mx-auto" data-aos="fade-left">
            <div class="d-flex flex-column flex-lg-row">
                <div class="w-100" style="height: 200px;width: 190px;"><a href="{% url 'users:segurity' %}"><i
                            class="material-icons" data-bss-hover-animate="pulse"
                            style="font-size: 139px;color: rgb(0,149,255);border-color: rgb(255,255,255);box-shadow: 0px 0px 0px;">security</i></a>
                </div>
                <div class="py-4 py-lg-0 px-lg-4">
                    <h4 style="color: rgb(255,255,255);">Seguridad</h4>
                    <p style="color: rgb(255,255,255);">Configure los ajustes y diferentes métodos de seguridad.&nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_main/templates/register.html
{% extends 'base/body.html' %}
{% load static %}
{% block content %}
<section class="register-photo" style="background: rgba(251,251,251,0);">
    <div class="form-container" style="margin-top: 40px;backdrop-filter: blur(0px) grayscale(0%);-webkit-backdrop-filter: blur(0px) grayscale(0%);border-radius: 20px;box-shadow: 10px 10px 20px 0px rgb(12,13,14);">
        <div class="image-holder" style="background: url(&quot;{% static 'img/puercoregisro.jpg' %} &quot;) center / cover no-repeat;"></div>
        <form method="post" action="." style="height: 525px;">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{action}}">
            <input type="hidden" name="next" value="{{next}}">
            <h2 class="text-center"><strong>{{title}}</strong>.</h2>
            <div>
                <input class="form-control" type="text" name="username" id="register_name" placeholder="Usuario" style="margin-bottom: 10px;">
            </div>
            <div>
                <input class="form-control" type="text" name="ci" id="CI" placeholder="Carnet de Identidad">
            </div>
            <div>
                <input class="form-control" type="tel" name="phone" placeholder="Teléfono" style="margin-top: 10px;">
            </div>
            <div>
                <input class="form-control" type="password" id="password_register" name="password1" placeholder="Contraseña" style="margin-top: 10px;">
            </div>
            <div>
                <input class="form-control" type="password" id="confirmPassword_register" name="password2" placeholder="Repetir contraseña" onchange="changePassword()" style="margin-top: 10px;"></div>
            
            <div class="form-group mb-3">
                <div class="form-check" style="margin-top: 10px;">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" data-bss-hover-animate="rubberBand">Estoy de acuerdo con los términos y condiciones.</label>
                    </div>
            </div>
            <div class="form-group mb-3">
                <button class="btn btn-primary d-block w-100" data-bss-hover-animate="pulse" id="submitButton" type="submit" style="color: rgb(255,255,255);background-color: #00b5a8;box-shadow: 1px 1px 6px 0px rgba(0,0,0,0.81);">Crear cuenta</button>
            </div>
            <a class="already" href="{% url 'users:login' %}">¿Ya tienes una cuenta? Inicia sesión aquí</a>
        </form>
        <script>
            {% if form.errors %}
                var errors = '';
                {% for field in form %}
                    {% for error in field.errors %}
                        errors += '{{error}}\n';  
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    errors += '{{error}}\n';
                {% endfor %}
                messaje_error(errors);
               
            {% endif %}
            
        </script>
        
    </div>
</section>
{% endblock  %}