app_main/urls.py
from django.urls import path
from .views import views, cards_view, transfer_view, service_view, destinatary_view, destinatary_view, history_view

app_name = 'system'

urlpatterns = [
     # Pagina de inicio
     path('', views.IndexView.as_view(), name='home'),
     # historial
     path('history/', history_view.HistorialView.as_view(), name='history'),
     
     path('terms_conditions/', views.TermsView.as_view(), name='terms_conditions'),
     path('contact/', views.ContactView.as_view(), name='contact'),
     path('main/', views.MainView.as_view(), name='main'),
     # Servicios
     path('service_list/', service_view.ServiceListView.as_view(), name='service_list'),
     path('service_create/', service_view.ServiceCreateView.as_view(), name='service_create'),
     path('service_update/<int:pk>', service_view.ServiceUpdateView.as_view(), name='service_update'),
     path('service_delete/<int:pk>', service_view.ServiceDeleteView.as_view(), name='service_delete'),
     path('service_pay/<int:pk>', service_view.ServicePayView.as_view(), name='service_pay'),
     # Tarjetas
     path('card_list/', cards_view.CardListView.as_view(), name='card_list'),
     path('card_create/',
          cards_view.CardCreateView.as_view(), name='card_create'),
     path('card_delete/<int:pk>',
          cards_view.CardDeleteView.as_view(), name='card_delete'),
     # Transferencias
     path('transfer_create/',
          transfer_view.TranferCreateView.as_view(), name='transfer_create'),
     path('transfer_list/',
          transfer_view.TranferListView.as_view(), name='transfer_list'),
     # Destinatarios
     path('destinatary_list/',
          destinatary_view.DestinataryListView.as_view(), name='destinatary_list'),
     path('destinatary_delete/<int:pk>',
          destinatary_view.DestinataryDeleteView.as_view(), name='destinatary_delete'),
     path('destinatary_create/',
          destinatary_view.DestinataryCreateView.as_view(), name='destinatary_create'),
     path('destinatary_update/<int:pk>',
          destinatary_view.DestinataryUpdateView.as_view(), name='destinatary_update')                    

]

app_users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', UsersLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    
    path('editprofile/<int:pk>/', UserUpdateView.as_view(), name='editprofile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('segurity/', SegurityUserView.as_view(), name='segurity')
]

project_EZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')),
    path('', include('app_users.urls'))
]

app_main/views/cards_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *


class CardListView(LoginRequiredMixin, ListView):
    model = User_Card
    template_name = 'card/credit_card.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        cards_list = User_Card.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Tarjetas'
        context['title'] = 'Agregar Tarjeta'
        context['entity'] = User_Card
        context['object_list'] = cards_list
        context['action'] = 'add'
        context['data'] = self.request.session.pop('data', None)

        return context


class CardCreateView(LoginRequiredMixin, CreateView):
    model = User_Card
    form_class = CardForm
    template_name = 'card/credit_card.html'
    success_url = reverse_lazy('system:card_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    card = Bank_DB.objects.get(
                        card_number=request.POST['card_number'])
                    if not card.associated:
                        if request.POST['pin'] == card.pin:
                            form.instance.user = self.request.user
                            form.instance.bank_type = card.bank_type
                            form.instance.currency_type = card.currency_type
                            form.instance.balance = card.balance
                            card.associated = True

                            card.save()
                            form.save()
                            data['form_is_valid'] = True
                        else:
                            data['error'] = 'Pin incorrecto'
                    else:
                        data['error'] = 'La tarjeta ya está asociada a un usuario!'
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'
        
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta de no existe'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'La tarjeta ha sido creada con éxito.'}
            print(request.session['data'])
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'User_Card'
        context['list_url'] = reverse_lazy('card_create')

        return context


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = User_Card
    success_url = reverse_lazy('system:card_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:

            user_card = User_Card.objects.get(id=self.object.id)
            bank_card = Bank_DB.objects.get(card_number=user_card.card_number)

            bank_card.associated = False
            bank_card.save()
        except:
            pass
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        
        context['title'] = 'Eliminar tarjeta'
        context['text'] = 'Estas seguro que desea eliminar la tarjta?'
        context['url_redirect'] = self.success_url
        return context
   
    

app_main/views/destinatary_view.py
from typing import Any, Dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *



class DestinataryListView(LoginRequiredMixin, ListView):
    model = Destinatary
    template_name = 'destinatary/destinary.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        destinatary_list = Destinatary.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Destinatarios'
        context['title'] = 'Agregar Destinatario'
        context['entity'] = Destinatary
        context['object_list'] = destinatary_list
        context['data'] = self.request.session.pop('data', None)
        context['action_update'] = 'edit'
        context['action'] = 'add'

        return context
    

class DestinataryCreateView(LoginRequiredMixin, CreateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(
                        card_number=number)
                    form.instance.user = self.request.user

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:
                        if destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)

                    form.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'

        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido creado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)
    

class DestinataryDeleteView(LoginRequiredMixin, DeleteView):
    model = Destinatary
    success_url = reverse_lazy('system:destinatary_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar destinatario'
        context['text'] = 'Está seguto de eliminar el destinatario?'
        context['url_redirect'] = reverse_lazy('system:destinatary_list')

        return context


class DestinataryUpdateView(LoginRequiredMixin, UpdateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(card_number=number)

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:

                        if self.object.associated_card == number or self.object.name == name:
                            pass
                        elif destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)
                       
                    form.save()
                    data['form_is_valid'] = True

                else:
                    data['error'] = form.errors    
                
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido actualizado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar destinatario'

        return context 

app_main/views/history_view.py
from itertools import chain
from django.contrib.contenttypes.models import ContentType
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Transfer, Service_Pay


class HistorialView(LoginRequiredMixin, ListView):
    model = Transfer
    template_name = 'historial.html'
    context_object_name = 'historial'

    def get_queryset(self):
        user = self.request.user
        transfers = Transfer.objects.filter(user=user)
        service_pays = Service_Pay.objects.filter(user=user, checked=True)

        queryset = sorted(chain(transfers, service_pays),
                          key=lambda i: i.date, reverse=True)
        for object in queryset:
            object.model_name = ContentType.objects.get_for_model(object).model
            print(object.model_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

app_main/views/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..mixins import IsSuperuserMixin

# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class MainView(LoginRequiredMixin, IsSuperuserMixin, TemplateView):
    template_name = 'main.html'


class TermsView(TemplateView):
    template_name = 'terms_conditions.html'

class ContactView(TemplateView):
    template_name = 'contactenos.html'          

app_main/templates/base/body.html
{% load static %}
{% include 'base/head.html' %}

<body style="background: url({% static 'img/774369.jpg' %}) top / cover no-repeat;">

    {% block header %}
    {% include 'base/header.html' %}

    {% endblock %}



    {% block content %}
    {% endblock %}


    {% block footer %}
    {% include 'base/footer.html' %}

    {% endblock %}

    {% block script %}
    <script>
        window.onbeforeunload = function () {
            cerrarSesion();
        };
    </script>
    {% endblock script %}

</body>

app_main/templates/base/footer.html
<footer style="background: rgba(87,88,88,0);">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item"></li>
                </ul>
                <p style="color: rgb(255,255,255);text-align: center;margin-bottom: 100px;">
                    <br>
                    <span style="color: rgb(108, 117, 125);">@ Xetid 2023.Todos los derechos reservados.</span>
                    <br>
                    <br>
                </p>
            </div>
        </div>
    </div>
</footer>

app_main/templates/base/head.html
{% load static %}
<!--LOS LINKS DEL CSS-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>enzona</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/swiper-icons.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/material-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/registrar.css' %}">
    <link rel="stylesheet" href="{% static 'css/Simple-Slider-swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylePage.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbarMODELO.css' %}">
    <link rel="stylesheet" href="{% static 'css/Principal.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Account-setting-or-edit-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/Profile-with-data-and-skills.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/poppinsfont.css' %}">
    <link rel="stylesheet" href="{% static 'css/contactenos.css' %} ">
    
    <!--LOS LINKS DEL JS-->
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/aos.min.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Simple-Slider-swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/Simple-Slider.js' %}"></script>
    <script src="{% static 'js/crud_tarjet.js' %}"></script>
    <script src="{% static 'js/crud%20user.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
    
    <script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
    <script src="{% static 'js/contactenos.js' %} "></script>
    <script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'js/servicios.js' %}"></script>
    <script src="{% static 'js/cerrar_sesion.js' %}"></script>
     
</head>

app_main/templates/base/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light navbar-expand-md py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'system:main' %}" style="font-size: 30px;"><span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon" style="background: url(&quot;{% static 'img/enzona%20-%20copia.jpg' %}&quot;) center / cover no-repeat;border-style: none;border-radius: 90px;transform: perspective(0px) scale(1.88);"></span><span style="color: #ffffff;margin-left: 10px;">Enzona</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" data-bss-hover-animate="pulse" href="{% url 'system:terms_conditions' %}" style="font-size: 20px;color: #ffffff;">Términos y condiciones</a></li>
                    <li class="nav-item"><a class="nav-link" data-bss-hover-animate="pulse" href="{% url 'system:contact' %}" style="font-size: 20px;color: #ffffff;">Contáctenos</a></li>
                    {% if user.is_authenticated %}
                        <div class="btn-group"  >
                            <button type="button" class="btn btn-primary"data-bss-hover-animate="pulse">Opciones </button>
                            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'users:segurity' %}">Seguridad</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'system:service_list' %}">Pago de Servicios</a></li>
                            <li><a class="dropdown-item" href="{% url 'system:history' %}">Historial</a></li>
                            <li><a class="dropdown-item" href="{% url 'system:transfer_list' %}">Transferencias</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'system:destinatary_list' %}">Mis Destinatarios</a></li>
                            <li><a class="dropdown-item" href="{% url 'system:card_list' %}">Mis tarjetas</a></li>
                            </ul>
                        </div>
                        <a class="btn btn-primary ms-md-2" role="button" href="/logout" style="font-size: 20px;">Cerrar Sesión</a>
                    {% else %}
                        <a class="btn btn-primary ms-md-2" role="button" href="/login" style="font-size: 20px;">Iniciar Sesión</a>
                        <a class="btn btn-primary ms-md-2" role="button" href="/register" style="font-size: 20px;">Registrarse</a>
                    {% endif %}
                    
                    
                </ul>
            </div>
        </div>
    </nav>

</header>

app_main/templates/base/scripts_alert.html
{% if data.success_message %}
<script>
    Swal.fire({
        icon: 'success',
        title: '{{ data.success_message }}',
        showConfirmButton: false,
        timer: 3000
    });
</script>
{% elif data.error_message %}
<script>
    Swal.fire({
        icon: 'error',
        title: '{{ data.error_message }}',
        showConfirmButton: true,
    });
</script>
{% endif %}
<script>
    window.onbeforeunload = function () {
        cerrarSesion();
    };
</script>