app_main/urls.py
from django.urls import path
from .views import views, cards_view, transfer_view, service_view, destinatary_view, destinatary_view, history_view

app_name = 'system'

urlpatterns = [
     # Pagina de inicio
     path('', views.IndexView.as_view(), name='home'),
     # historial
     path('history/', history_view.HistorialView.as_view(), name='history'),
     
     path('terms_conditions/', views.TermsView.as_view(), name='terms_conditions'),
     path('contact/', views.ContactView.as_view(), name='contact'),
     path('main/', views.MainView.as_view(), name='main'),
     # Servicios
     path('service_list/', service_view.ServiceListView.as_view(), name='service_list'),
     path('service_create/', service_view.ServiceCreateView.as_view(), name='service_create'),
     path('service_update/<int:pk>', service_view.ServiceUpdateView.as_view(), name='service_update'),
     path('service_delete/<int:pk>', service_view.ServiceDeleteView.as_view(), name='service_delete'),
     path('service_pay/<int:pk>', service_view.ServicePayView.as_view(), name='service_pay'),
     # Tarjetas
     path('card_list/', cards_view.CardListView.as_view(), name='card_list'),
     path('card_create/',
          cards_view.CardCreateView.as_view(), name='card_create'),
     path('card_delete/<int:pk>',
          cards_view.CardDeleteView.as_view(), name='card_delete'),
     # Transferencias
     path('transfer_create/',
          transfer_view.TranferCreateView.as_view(), name='transfer_create'),
     path('transfer_list/',
          transfer_view.TranferListView.as_view(), name='transfer_list'),
     # Destinatarios
     path('destinatary_list/',
          destinatary_view.DestinataryListView.as_view(), name='destinatary_list'),
     path('destinatary_delete/<int:pk>',
          destinatary_view.DestinataryDeleteView.as_view(), name='destinatary_delete'),
     path('destinatary_create/',
          destinatary_view.DestinataryCreateView.as_view(), name='destinatary_create'),
     path('destinatary_update/<int:pk>',
          destinatary_view.DestinataryUpdateView.as_view(), name='destinatary_update')                    

]

project_EZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')),
    path('', include('app_users.urls'))
]

app_main/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class CardForm(ModelForm):

    class Meta:
        model = User_Card
        fields = ['card_number', 'pin']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['class'] = 'form_control'
            form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['card_number'].widget.attrs['autofocus'] = True

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data


class TransferForm(ModelForm):

    class Meta:
        model = Transfer
        fields = ['origin_card', 'dest_card',
                  'import_transfer']
        

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data


class ServiceForm(ModelForm):

    class Meta:
        model = Service_Pay
        fields = ['service_id', 'service_type',
                  'propietary']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data


class ServicePayForm(ModelForm):

    class Meta:
        model = Service_Pay
        fields = []

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data


class DestinataryForm(ModelForm):

    class Meta:
        model = Destinatary
        fields = ['name', 'associated_card']
        

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data

app_main/views/cards_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *


class CardListView(LoginRequiredMixin, ListView):
    model = User_Card
    template_name = 'card/credit_card.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        cards_list = User_Card.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Tarjetas'
        context['title'] = 'Agregar Tarjeta'
        context['entity'] = User_Card
        context['object_list'] = cards_list
        context['action'] = 'add'
        context['data'] = self.request.session.pop('data', None)

        return context


class CardCreateView(LoginRequiredMixin, CreateView):
    model = User_Card
    form_class = CardForm
    template_name = 'card/credit_card.html'
    success_url = reverse_lazy('system:card_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    card = Bank_DB.objects.get(
                        card_number=request.POST['card_number'])
                    if not card.associated:
                        if request.POST['pin'] == card.pin:
                            form.instance.user = self.request.user
                            form.instance.bank_type = card.bank_type
                            form.instance.currency_type = card.currency_type
                            form.instance.balance = card.balance
                            card.associated = True

                            card.save()
                            form.save()
                            data['form_is_valid'] = True
                        else:
                            data['error'] = 'Pin incorrecto'
                    else:
                        data['error'] = 'La tarjeta ya está asociada a un usuario!'
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'
        
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta de no existe'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'La tarjeta ha sido creada con éxito.'}
            print(request.session['data'])
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'User_Card'
        context['list_url'] = reverse_lazy('card_create')

        return context


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = User_Card
    success_url = reverse_lazy('system:card_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:

            user_card = User_Card.objects.get(id=self.object.id)
            bank_card = Bank_DB.objects.get(card_number=user_card.card_number)

            bank_card.associated = False
            bank_card.save()
        except:
            pass
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        
        context['title'] = 'Eliminar tarjeta'
        context['text'] = 'Estas seguro que desea eliminar la tarjta?'
        context['url_redirect'] = self.success_url
        return context
   
    

app_main/views/destinatary_view.py
from typing import Any, Dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from ..models import *
from ..forms import *



class DestinataryListView(LoginRequiredMixin, ListView):
    model = Destinatary
    template_name = 'destinatary/destinary.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        destinatary_list = Destinatary.objects.filter(
            user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Mis Destinatarios'
        context['title'] = 'Agregar Destinatario'
        context['entity'] = Destinatary
        context['object_list'] = destinatary_list
        context['data'] = self.request.session.pop('data', None)
        context['action_update'] = 'edit'
        context['action'] = 'add'

        return context
    

class DestinataryCreateView(LoginRequiredMixin, CreateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()

                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(
                        card_number=number)
                    form.instance.user = self.request.user

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:
                        if destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)

                    form.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'

        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido creado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)
    

class DestinataryDeleteView(LoginRequiredMixin, DeleteView):
    model = Destinatary
    success_url = reverse_lazy('system:destinatary_list')
    template_name = 'eliminar.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar destinatario'
        context['text'] = 'Está seguto de eliminar el destinatario?'
        context['url_redirect'] = reverse_lazy('system:destinatary_list')

        return context


class DestinataryUpdateView(LoginRequiredMixin, UpdateView):
    model = Destinatary
    form_class = DestinataryForm
    template_name = 'destinatary/destinary.html'
    success_url = reverse_lazy('system:destinatary_list')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    number=int(request.POST['associated_card'])
                    name=request.POST['name']
                    card = Bank_DB.objects.get(card_number=number)

                    destinatary_list = Destinatary.objects.filter(user=self.request.user)
                    for destinatary in destinatary_list:

                        if self.object.associated_card == number or self.object.name == name:
                            pass
                        elif destinatary.associated_card == number:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con esta tarjeta asociada!'}
                            return redirect(self.success_url)
                        elif destinatary.name == name:

                            request.session['data'] = {
                            'error_message': 'Ya existe un destinatario con este nombre!'}
                            return redirect(self.success_url)
                       
                    form.save()
                    data['form_is_valid'] = True

                else:
                    data['error'] = form.errors    
                
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Bank_DB.DoesNotExist:
            data['error'] = 'La tarjeta no existe!'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El destinatario ha sido actualizado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar destinatario'

        return context 

app_main/views/history_view.py
from itertools import chain
from django.contrib.contenttypes.models import ContentType
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Transfer, Service_Pay


class HistorialView(LoginRequiredMixin, ListView):
    model = Transfer
    template_name = 'historial.html'
    context_object_name = 'historial'

    def get_queryset(self):
        user = self.request.user
        transfers = Transfer.objects.filter(user=user)
        service_pays = Service_Pay.objects.filter(user=user, checked=True)

        queryset = sorted(chain(transfers, service_pays),
                          key=lambda i: i.date, reverse=True)
        for object in queryset:
            object.model_name = ContentType.objects.get_for_model(object).model
            print(object.model_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

app_main/views/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..mixins import IsSuperuserMixin

# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class MainView(LoginRequiredMixin, IsSuperuserMixin, TemplateView):
    template_name = 'main.html'


class TermsView(TemplateView):
    template_name = 'terms_conditions.html'

class ContactView(TemplateView):
    template_name = 'contactenos.html'          

app_main/templates/card/credit_card.html
{% extends 'base/body.html' %}


{% block content %}
<div class="row justify-content-center" style="padding-top: 40px;padding-right: 20px;padding-bottom: 20px;">
    <div class="col-xl-10 col-xxl-9">
        <div class="card shadow" style="background: rgb(255, 255, 255);border-radius: 10px;">
            <div class="card-header d-flex justify-content-center align-items-center flex-wrap justify-content-sm-between gap-3">
                <h5 class="display-6 text-nowrap text-capitalize mb-0">{{title_list}}</h5>
                <div><button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" id="btn-abrir-modal"> Nueva Tarjeta </button>
                    <div class="modal fade" role="dialog" tabindex="-1" id="exampleModal" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="fs-5 modal-title" id="exampleModalLabel">{{title}}</h1>
                                    <button class="btn-close" type="button" aria-label="Close" data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <form method="POST" action="{% url 'system:card_create' %}" id="formulario">
                                      {% csrf_token %}
                                      <input type="hidden" name="action" value="{{action}}">
                                      <div class="row">
                                        <div class="col-12 col-sm-6">
                                          <label class="col-form-label form-label" for="card_number">Numero:</label>
                                        </div>
                                        <div class="col-12 col-sm-6">
                                          <input
                                            class="form-control"
                                            type="text"
                                            id="numero_card"
                                            name="card_number"
                                            
                                            
                                          />
                                          
                                        </div>
                                      </div>
                                      <div class="row">
                                        <div class="col-12 col-sm-6">
                                          <label class="col-form-label form-label" for="pin">Pin:</label>
                                        </div>
                                        <div class="col-12 col-sm-6">
                                          <input
                                            class="form-control"
                                            id="pin_card"
                                            type="number"
                                            name="pin"
                                            
                                            
                                            
                                          />
                                          
                                        </div>
                                      </div>
                                      <div class="modal-footer">
                                        <button class="btn btn-danger" type="button" data-bs-dismiss="modal" id="btn-cerrar-modal">Cancelar</button>
                                        <button class="btn btn-success" id="Guardar" type="submit">Aceptar</button>
                                      </div>
                                    </form>                                  
                                  </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>No.List</th>
                                <th>Numero</th>
                                <th>Moneda</th>
                                <th>Banco</th>
                                <th>Saldo</th>
                                <th class="text-center">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for card in object_list %}
                                
                                        <tr>
                                            <td class="text-truncate" style="max-width: 200px;">{{card.id}}</td>
                                            <td class="text-truncate" style="max-width: 200px;">{{card.card_number}}</td>
                                            <td>{{card.currency_type}}</td>
                                            <td>{{card.bank_type}}</td>
                                            <td>{{card.balance}}</td>
                                            <td class="text-center">
                                                
                                                <a class="btn btn-danger" href="{% url 'system:card_delete' card.id %}"  type="button" >
                                                    <i class="material-icons ">delete</i>
                                                </a>
                                                
                                            </td>
                                        </tr>
                                   
                                
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
<div style="height: 350px;position: static;"></div>

<script>
  const inputNumeroCard = document.getElementById('numero_card');
  const inputPinCard = document.getElementById('pin_card');
    inputNumeroCard.addEventListener('input', validarNumeroCard);
    inputPinCard.addEventListener('input', validarPinCard);
    
    function validarNumeroCard() {
      const regexSoloNumeros = /^[0-9]+$/;
      if (!regexSoloNumeros.test(inputNumeroCard.value)) {
        inputNumeroCard.value = inputNumeroCard.value.replace(/[^\d]/g, '');
      }
      if (inputNumeroCard.value.length > 16) {
        inputNumeroCard.value = inputNumeroCard.value.slice(0, 16);
      }
    }
    function validarPinCard() {
      const regexSoloNumeros = /^[0-9]+$/;
      if (!regexSoloNumeros.test(inputPinCard.value)) {
        inputPinCard.value = inputPinCard.value.replace(/[^\d]/g, '');
      }
      if (inputPinCard.value.length > 4) {
        inputPinCard.value = inputPinCard.value.slice(0, 4);
      }
    }
</script>


{% endblock  %}

app_main/templates/card/eliminar_card.html
{% extends 'base/body.html' %}

{% block content %}
<div id="main" style="border-radius: 0px;">
    <div class="text-center" data-aos="fade-down" style="border-radius: 15px;height: 500px;">
        <p class="text-center" style="font-size: 20px;">{{title}}</p>
        <form method="post" >
            {% csrf_token %} 
            <div class="text-center px-6 py-6" >
                <div class="text-center px-6 py-6" >
                    <p>Estas seguro que desea eliminar la siguiente tarjeta? {{object}}</p>
                </div>
                <a type="button" href="{% url 'system:card_list' %}" class="btn btn-secondary">Cancelar </a>
                <button type="submit" class="btn btn-danger">Confirmar </button>   
            </div>     
           </form>
        
        </div>
</div>

{% endblock  %}